import type { AppSettings } from "./persisted-types";

export const DEFAULT_SETTINGS: AppSettings = {
  autoLockMinutes: 15,
  lockOnSleep: true,
  lockOnWindowBlur: false,
  clipboardClearSeconds: 30,
  network: {
    liveApiUrl: "https://rpc.qubic.org/live/v1",
    queryApiUrl: "https://rpc.qubic.org/query/v1",
    name: "mainnet",
  },
  activeVaultId: null,
  activeAccountIndex: 0,
  hideBalances: false,
  approvedDapps: [],
  currency: "USD",
  tickOffset: 10,
  themeMode: "dark",
  debugMode: false,
  biometricVaultIds: [],
  fontPair: "space-grotesk",
  accentColor: "green",
  customScheme: null,
  notificationsEnabled: false,
  notifyOnReceived: true,
  notifyOnSent: true,
  notifyOnConfirmed: true,
  notifyOnMissedConfirmations: true,
  notifyOnLargeIncoming: false,
  notifyOnPriceAlerts: false,
  notifyWhenLocked: false,
  largeIncomingThreshold: "",
  priceAlertAbove: "",
  priceAlertBelow: "",
  pollingIntervalActiveMs: 5_000,
  pollingIntervalBackgroundMs: 10_000,
  pollingIntervalTrayMs: 15_000,
  pollingIntervalLockedMs: 20_000,
  hideToTray: false,
  sponsorAttribution: "anonymous",
  allowBlurLockBypass: false,
  requirePasswordForBurn: false,
  requireBiometricForSeedReveal: false,
  highValueSendThreshold: "",
  exportSigningPrivateJwk: null,
  lowBalanceThreshold: "",
  customPriceFeedUrl: "",
};
